#!/usr/bin/env python

from Classes_Pymatgen import *
import sys

c = Chgcar.from_file('CHGCAR')

x = (float(sys.argv[1]) * len(c.get_axis_grid(0)))
y = (float(sys.argv[2]) * len(c.get_axis_grid(1)))

csv_data = 'z, Charge (e-/A)\n'
data = c.data['total']

for z in range(len(c.get_axis_grid(2))):
  csv_data = csv_data + '{},{}\n'.format(c.get_axis_grid(2)[z], data[x][y][z])
  
with open('chgdata.csv', 'w') as f:
  f.write(csv_data)
